server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://lovelynephewdb.cz997nixexiw.ap-northeast-2.rds.amazonaws.com:3306/lovelynephewdb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: admin
    password: 1q2w3e4r
    
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true

mybatis:
  mapper-locations:
  - /mappers/**/*.xml

