pipeline {
    agent any
    
    tools {
        maven "maven-3.8.7"
    }

    environment {
        imagename = "donguk585/lovelynephew"
        registryCredential = 'docker-hub'
        dockerImage = ''
    }

    stages {
        stage('Prepare') {
          steps {
            echo 'Clonning Repository'
            git url: 'git@github.com:lovelynephew/lovelynephew.git',
              branch: 'main',
              credentialsId: 'github'
            }
            post {
             success {
               echo 'Successfully Cloned Repository'
             }
           	 failure {
               error 'This pipeline stops here...'
             }
          }
        }

        stage('Bulid Maven') {
          steps {
            echo 'Bulid Maven'
            dir('.'){
            	sh "cd kids-mall/kids-mall; mvn -Dmaven.test.failure.ignore=true clean package"
            }
          }
          post {
            failure {
              error 'This pipeline stops here...'
            }
          }
        }

        stage('Bulid Docker') {
          steps {
            echo 'Bulid Docker'

            script {
                dockerImage = docker.build imagename, "-f ./kids-mall/kids-mall/Dockerfile ."
            }
          }
          post {
            failure {
              error 'This pipeline stops here...'
            }
          }
        }

        stage('Push Docker') {
          steps {
            echo 'Push Docker'
            script {
                docker.withRegistry( '', registryCredential) {
                    dockerImage.push()
                }
            }
          }
          post {
            failure {
              error 'This pipeline stops here...'
            }
          }
        }

    }
	post {
        success {
            discordSend description: "빌드 알림",
            footer: "Jenkins 빌드가 성공했습니다.",
            link: env.BUILD_URL, result: currentBuild.currentResult,
            title: "Jenkins Build",
            webhookURL: "https://discord.com/api/webhooks/1181590407612747848/2Dw4EahssAzu5eEEL71VwkspJcAff_nwIPvrBSy2NOSH_da7kl-0fPFPG63iaH3RLuD5"
        }
        failure {
            discordSend description: "빌드 알림",
            footer: "Jenkins 빌드가 실패했습니다.",
            link: env.BUILD_URL, result: currentBuild.currentResult,
            title: "Jenkins Build",
            webhookURL: "https://discord.com/api/webhooks/1181590407612747848/2Dw4EahssAzu5eEEL71VwkspJcAff_nwIPvrBSy2NOSH_da7kl-0fPFPG63iaH3RLuD5"
        }
    }
}