server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    additional-tld-skip-patterns: "*.jar"    
    

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 558240524548-kl51ok2aqpns1j2o8ib04j6o4gl23iml.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          kakao:
            client-id: 67adb09794071b8121a790071ea6b3ce
            redirect-uri: http://localhost:8888/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
            - profile_nickname
            - account_email
            - gender
            - birthday
            client-name: Kakao
          naver:
            client-id: nCCEZ1YO3BX2R47IuW3S
            client-secret: ys9448c9Wz
            scope:
            - email
            - name
            - gender
            - birthday
            - birthyear
            - mobile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8888/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            

    
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/ #JSP 파일이 위치할 기본 위치 설정
      suffix: .jsp

  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    view-names: thymeleaf/*

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://lovelynephewdb.cz997nixexiw.ap-northeast-2.rds.amazonaws.com:3306/lovelynephewdb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: admin
    password: 1q2w3e4r
    
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true
      
  main:
    allow-bean-definition-overriding: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: yeonho4698@gmail.com
    password: xmftlpcafacjmyux
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          auth: true
          starttls:
            enable: true

mybatis:
  mapper-locations:
  - /mappers/**/*.xml
  
coolsms:
  api:
    key: NCSZRNFDGXSSFQHI
    secret: TEAVABUFTSMZJLUEOJRJCANI8V3OHN7C
    url: https://api.coolsms.co.kr
